steps:
  # Build the container image
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "sijiewang/pngen:ai-toolkit",
        "--build-arg",
        "HF_TOKEN=${_HF_TOKEN}",
        ".",
      ]

  # Login to Docker Hub
  - name: "gcr.io/cloud-builders/docker"
    args: ["login", "-u", "${_DOCKER_USERNAME}", "-p", "${_DOCKER_PASSWORD}"]

  # Push the container image to Docker Hub
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "sijiewang/pngen:ai-toolkit"]

images:
  - "sijiewang/pngen:ai-toolkit"

options:
  logging: CLOUD_LOGGING_ONLY
