steps:
  # Build the container image
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "sijiewang/pngen:ai-toolkit",
        "--build-arg",
        "HF_TOKEN=${_HF_TOKEN}",
        ".",
      ]

  # Push the container image to Docker Hub
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "sijiewang/pngen:ai-toolkit"]
    env:
      - "DOCKER_USERNAME=${_DOCKER_USERNAME}"
      - "DOCKER_PASSWORD=${_DOCKER_PASSWORD}"

images:
  - "sijiewang/pngen:ai-toolkit"

options:
  logging: CLOUD_LOGGING_ONLY
